### ISSUE TITLE
TFloatSeq.to_dataframe() returns broken dataframe

### ISSUE THREAD

**Issue by anitagraser** [MobilityDB/PyMEOS#14]
I've been following up on the distance calculations. To test them, I'm using the generalized trajectories, calculating the distance between generalization results from PyMEOS and Movingpandas. Everything works fine with the distance calculations itself, resulting in a TFLoatSeq:
![image](https://user-images.githubusercontent.com/590385/221552944-59d9f2f7-787d-47af-a435-db9165495794.png)

However, in the next step, I'm running into issues converting the TFloatSeq back to a dataframe:
![image](https://user-images.githubusercontent.com/590385/221553045-6b576e2a-7602-437a-944f-382f9a750335.png)

You can find the notebook at: 
https://github.com/anitagraser/PyMEOS/blob/tfloatseq-to-seq/pymeos_examples/MovingPandas/mpd-to-pymeos.ipynb

**Comment by anitagraser** [comment]
Similarly, the values function also only returns a list of bound methods: 

![image](https://user-images.githubusercontent.com/590385/221555319-9ae1d615-19bf-441d-b048-b1e687c75e6e.png)

**Comment by Diviloper** [comment]
Thanks for letting us know. There were some calls to methods that used to be annotated as properties that were not properly changed.
This issue is fixed in 59f8bda272b0bbce86ca8a176b588e791b12e386 and is published as a [patch version (1.1.2.post6)](https://pypi.org/project/pymeos/) in PyPI.

The example you provided is working properly now:
![image](https://user-images.githubusercontent.com/43449526/221720305-217c88a9-5d47-4700-b09b-1281d8a4c45e.png)
![image](https://user-images.githubusercontent.com/43449526/221720326-dafaf2f9-9f20-4386-8f69-4a77da2ab44d.png)

**Comment by anitagraser** [comment]
Oh, I found another such issue: 

![image](https://user-images.githubusercontent.com/590385/221871433-a53c9b52-8a56-42dd-83b0-0a2c33e0db90.png)

**Comment by Diviloper** [comment]
Thanks! I had checked the usages within the package code but forgot to check the examples.
Working on it.

**Comment by Diviloper** [comment]
The examples are fixed in 46e0312b0af07e68cce1894684dbb578c597cc14.
