### ISSUE TITLE
Difference in percentage of point retention in version `1.1.2.post6` vs `1.1.3rc1`

### ISSUE THREAD

**Issue by mitirmizi** [MobilityDB/PyMEOS#31]
When I run the example notebook: `PyMEOS/pymeos_examples/PyMEOS_Examples/AIS.ipynb` I get different results for the code cell: "Here we can see that PyMEOS has been able to reduce the number of points stored (and thus memory used) without losing any information.".
```python
comparison = pd.concat(
    [
        ais.groupby("mmsi")["t"].count().rename("original #points"),
        trajectories["trajectory"]
        .apply(lambda t: t.num_instants())
        .rename("PyMEOS #points"),
    ],
    axis=1,
)
comparison["Points kept (%)"] = (
    comparison["PyMEOS #points"] / comparison["original #points"] * 100
)
comparison
```

When I run this code with PyMeos 1.1.2.post6 I get:
![Screenshot from 2024-02-24 04-00-47](https://github.com/MobilityDB/PyMEOS/assets/22791921/4b4d3cbd-97dd-466d-a112-7bcccea9e334)

But when I run the same cell using PyMeos 1.1.3rc1 I get:
![Screenshot from 2024-02-24 02-38-28](https://github.com/MobilityDB/PyMEOS/assets/22791921/a6356c0d-3700-47f0-9ef1-abda2e782441)

As it can be seen for the mmsi 148 the points kept are ~ 63% for PyMeos 1.1.2.post6 but are ~ 93% for PyMeos 1.1.3rc1.

**My question:** Why is this happening? Is this normal?

**Comment by Diviloper** [comment]
It is normal. Version `1.1.2.post6` was bundled with a version of MEOS where the normalization tolerance was `1.0e-05`, but this was changed to `1.0e-06`, which is the one used by the current versions of MEOS (and therefore also PyMEOS). 
To make sure, I just compiled MEOS with the old tolerance value and ran the examples, and indeed the results are the same as with `1.1.2.post6`:
![image](https://github.com/MobilityDB/PyMEOS/assets/43449526/2ed8ff88-2812-4a06-a20f-a891c68d5b36)
If further simplification is desired, you can use the [simplification functions](https://github.com/MobilityDB/PyMEOS/blob/5452e3c4b3b4c464ebf8e3e9bb633de7ef769bb7/pymeos/pymeos/mixins/simplify.py#L15) available for the `TFloat` and `TPoint` subclasses. For example:
![image](https://github.com/MobilityDB/PyMEOS/assets/43449526/ec3e42f0-1b6a-4e20-aa97-e1860fa317e4)
Note that the simplified points differ from the originals because the algorithm is not exactly the same, and here we are simplifiying the normalized sequences, not the original.
